# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on: ["push", "pull_request"]

name: Coveralls GitHub Action

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: [4.0, 4.2, 4.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci
    - run: npm run coverage
      env:
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    - uses: coverallsapp/github-action@v1.1.2
      with:
        # 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Path to lcov file
        path-to-lcov: ./coverage/lcov.info # default is ./coverage/lcov.info
        # Job flag name, e.g. "Unit", "Functional", or "Integration". Will be shown in the Coveralls UI.
        flag-name: # optional
        # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
        parallel: # optional
        # Set to true for the last action when using "parallel: true".
        parallel-finished: # optional
        # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
        coveralls-endpoint: # optional, default is https://coveralls.io
        # The root folder of the project that originally ran the tests
        base-path: # optional
